<? include ("include/inner-menu.php");?>
<? include ("include/left.php");?>
		<table width="710" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td>&nbsp;</td>
                    </tr>
                    <tr>
                      <td>&nbsp;</td>
                    </tr>
                    <tr>
                      <td ><table width="90%" border="0" align="center" cellpadding="0" cellspacing="0">
                        <tr>
                          <td class="page-header">Contact Us</td>
                        </tr>
                        <tr>
                          <td ><table width="90%" border="0" align="right" cellpadding="0" cellspacing="0">
                            <tr>
                              <td colspan="2">Thank you for visiting our Web site. Please  fill out the following form to request information about our products  and services or  e-mail us at <A href="mailto:info@tutorsonwheels.com">info@tutorsonwheels.com</A> to provide feedback about our site. When you are  finished, click the 'Submit' button to send us your message. You will  see a confirmation below.</td>
                            </tr>
                            <tr>
                              <td colspan="2">&nbsp;</td>
                            </tr>
                            <tr>
                              <td colspan="2" align="center"><form action="mailcontact.php" method="post" onSubmit="return validate(this)">
                                <!-- submit and end form -->
                                <table cellpadding="2" width="100%" border="0">
                                  <tbody>
                                    <tr>
                                      <td>                              
                                      <td align="right" ><span style="color: #ff0000">* Required Fields </span>
                                                                  <tr>
                                                                    <td width="30%"><span style="color: #ff0000">*</span> First Name:&nbsp;
                                                                    <td ><input name=
"firstname" class="input" id="firstname" maxlength="50">
                                                                                                                                  <tr>
                                                                                                                                    <td nowrap="nowrap"><span style="color: #ff0000">*</span> Last Name:                                                                                                                                   
                                                                                                                                    <td ><input name=
"lastname" class="input" id="lastname" maxlength="50">                                                                                                                                  
                                    <tr>
                                      <td nowrap="nowrap"><span style="color: #ff0000">*</span> Organization Name:
                                      <td ><input name=
"organizationname" class="input" id="organizationname" maxlength="50">
                                      <tr>
                                                                                                                                                                  <td><span style="color: #ff0000">*</span> Street Address: 
                                                                                                                                                                  <td ><input name="address1" class="input" id="address1" maxlength="25">
                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                          <td>                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                          <td ><input name="address2" class="input" id="address2" maxlength="25">
                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                          <td><span style="color: #ff0000">*</span> Town / City:&nbsp;
                                                                                                                                                                                                                                                                                                                          <td ><input name="city" class="input" id="city" maxlength="20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td >State:&nbsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td ><select name=
"state" class="input" id="state">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <!--																					<option>AL
																						<option>AK
																							<option>AR
																								<option>AZ
																								<option>CA
																								<option>CO
																								<option>CT
																								<option>DC
																								<option>DE
																								<option>FL
																								<option>GA
																								<option>HI
																								<option>IA
																								<option>ID
																								<option>IL
																								<option>IN
																								<option>KS
																								<option>KY
																								<option>LA
																								<option>MA
																								<option>MD
																								<option>ME
																								<option>MI
																								<option>MN
																								<option>MS
																								<option>MO
																								<option>MT
																								<option>NC
																								<option>ND
																								<option>NE
																								<option>NH
																								<option>NJ
																								<option>NV
																								<option>NM-->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option selected>NY
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <!--<option>OH
																								<option>OK
																								<option>OR
																								<option>PA
																								<option>RI
																								<option>SC
																								<option>SD
																								<option>TN
																								<option>TX
																								<option>UT
																								<option>VT
																								<option>VA
																								<option>WA
																								<option>WI
																								<option>WV
																								<option>WY-->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td><span style="color: #ff0000">*</span> Zip Code/Postal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Code:&nbsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td ><input name="zipcode" class="input" id="zipcode" maxlength="5" onKeyUp="isRule(this,objWholeNumber)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td>Country:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td ><select size="1" class="select" name="country" id="country" onChange="populateStates(this.options[this.selectedIndex].value);">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="United States|223">United States</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td><span style="color: #ff0000">*</span> Email:&nbsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td ><input name="email" class="input" id="email" maxlength="60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td><span style="color: #ff0000">*</span> Work Phone:&nbsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <td ><input name="phone" class="input" id="phone" maxlength="10" onKeyUp="isRule(this,objWholeNumber)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td>Fax:&nbsp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td ><input name="fax" class="input" id="fax" maxlength="10" onKeyUp="isRule(this,objWholeNumber)">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                      <td>Subject:&nbsp;
                                      <td ><input name=
"subject" class="input" id="subject" maxlength="20">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td valign="top">Message:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td ><textarea name="message" cols=
"27" rows="3" class="input" id="message"></textarea>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td align="center">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td><input name="submit" type="submit" value="Submit">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input name="reset"
type="reset" id="reset" value="Reset">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                <p>
                                                            </form></td>
                            </tr>
							<tr>
							  <td height="20" colspan="2" valign="top"><hr width="100%" size="1" noshade></td>
						    </tr>
							<tr>
							  <td colspan="2" valign="top"><h2 class="subhd-school">Direction</h2>
							    <p><strong>BY AUTOMOBILE</strong><br>
                                    <strong><br>
                                      From the West:</strong> Grand    Central Parkway to Van Wyck expressway to Harry Van Arsdale Jr. Ave.  (Jewel Ave.)  Exit. Turn right on to Jewel    Avenue (which becomes 69th road). Continue to Yellowstone Boulevard,  make a left turn and cross Queens    Boulevard. Continue one block to the service road  of Queens Boulevard  and make a left turn. Make a right turn onto 69th Road and a right onto Austin Street.  Street and Garage parking are available.<br>
  <br>
  <strong>From the East:</strong> Grand Central Parkway to Harry Van Arsdale, Jr. Ave.  (Jewel Avenue)  Exit. Turn left on the service road. At traffic light, turn left on to Jewel Avenue (which  becomes 69th Road).  Continue to Yellowstone Boulevard,  make a left turn and cross Queens    Boulevard. Continue one block make a right turn  onto 69th Road  and right onto Austin Street.  Street and Garage parking are available. <br>
  <strong><br>
    BY SUBWAY</strong><br>
							      E,F,G, or R train to 71st Avenue/Continental Avenue, Forest Hills. Walk one block south on Continental Avenue to Austin Street and turn right. <br>
  <a href="http://mta.info/nyct/maps/subwaymap.pdf" target="_blank">View MTA New  York City Subway Map</a> <br>
  <strong><br>
    BY THE LONG ISLAND RAIL ROAD</strong><br>
							      Take The Long Island Railroad to the Forest   Hills Station. Walk one block north on Continental Avenue to Austin Street and turn left.<br>
  <a href="http://mta.info/lirr/html/lirrmap.htm" target="_blank">View MTA Long Island Rail Road  Map</a> <br>
  <strong><br>
    BY BUS</strong><br>
							      The Q-23 bus stops in front of the College.<br>
						      The Q-60 bus stops at Yellowstone and Queens Boulevards. Walk one block south  on Yellowstone Boulevard  to Austin Street  and turn left.</p></td>
						    </tr>
							<tr>
							  <td colspan="2">&nbsp;</td>
						    </tr>
							<tr>
                              <td colspan="2"><hr width="100%" size="1" noshade>
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                  <tr>
                                    <td width="115"><a href="hireatutor.php" target="_blank"><img src="images/btn-hireatotur.gif" alt="Hire a Tutor" width="104" height="24" border="0" title="Hire a Tutor"></a></td>
                                    <td align="left"><span style="font-weight: bold">OR </span>Call:&nbsp;&nbsp; <span class="red-font">(718) 268-0092&nbsp;&nbsp; <span style="color: #000000">/&nbsp;</span>&nbsp; (718) 268-0133&nbsp;&nbsp; <span style="color: #000000">/&nbsp;&nbsp;</span> (877)-Tutor-NY</span></td>
                                  </tr>
                                </table></td>
                            </tr>
                            

                          </table></td>
                        </tr>
                        <tr>
                          <td >&nbsp;</td>
                        </tr>
                      </table></td>
                    </tr>
                  </table></td>
				</tr>
			</table>
			<script language="javascript">
			function validate(f)
			{
				arr = Array('0','1','2','3','5','7','9','10')
				msgarr = Array('First Name','Last Name','Organization Name','Street Address','Town / City','Zip Code/Postal Code','Email','Work Phone Number')
				for(i=0;i<arr.length;i++)
				{
					if(trim(f.elements[arr[i]].value)=="")
					{
						alert('Please Enter ' + msgarr[i])
						f.elements[arr[i]].focus()
						return false
					}
				}
				if(!trim(f.email.value).match(regexpforemail))
				{
					alert("Please Enter Valid Email")
					f.email.select()
					return false
				}
				return true
			}
			</script>
			<? include ("include/bottom.php");?>