DROP TABLE IF EXISTS `#__googlemap`;
CREATE TABLE IF NOT EXISTS `#__googlemap` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `greeting` varchar(500) NOT NULL,
  `apiKey` varchar(200) NOT NULL,
  `mapHeight` int(4) NOT NULL,
  `mapWidth` int(4) NOT NULL,
  `mapEmail` varchar(250) NOT NULL,
  `mapFax` varchar(35) NOT NULL,
  `mapTp` varchar(35) NOT NULL,
  `mapPhone` varchar(35) NOT NULL,
  `mapAddress` text NOT NULL,
  `mapLatitude` varchar(35) NOT NULL,
  `mapLongitude` varchar(35) NOT NULL,
  `mapViewHeight` varchar(35) NOT NULL,
  `mapView` varchar(35) NOT NULL,
  `mapPointImg` varchar(400) NOT NULL,
  `companyVideoProfile` varchar(100) NOT NULL,
  `companySpamcheck` int(1) NOT NULL,
  `map3dWidth` int(11) NOT NULL,
  `map3dHeight` int(11) NOT NULL,
  `map3dview` int(1) NOT NULL,
  `mapYaw` double NOT NULL,
  `mapPitch` int(11) NOT NULL,
  `mapEmailTxtBox` varchar(200) NOT NULL,
  `mapFaxTxtBox` varchar(200) NOT NULL,
  `mapTpTxtBox` varchar(200) NOT NULL,
  `mapPhoneTxtBox` varchar(200) NOT NULL,
  `defaultTxtBox` varchar(200) NOT NULL,
  `defaultTxt` text NOT NULL,
  `mapComInfoForm` int(11) NOT NULL,
  `mapContForm` int(11) NOT NULL,
  `mapGoogleForm` int(11) NOT NULL,
  `mapDGoogleForm` int(11) NOT NULL,
  `mapVideoForm` int(11) NOT NULL,
  `mapEnterYourNameForm` varchar(200) NOT NULL,
  `mapEnterEmailForm` varchar(200) NOT NULL,
  `mapEnterSubForm` varchar(200) NOT NULL,
  `mapEnterMessForm` varchar(200) NOT NULL,
  `mapEnterSpameForm` varchar(200) NOT NULL,
  `mapEnterEmailCopForm` varchar(200) NOT NULL,
  `mapEnterBtnForm` varchar(200) NOT NULL,
  `mapWidthOfForm` int(11) NOT NULL,
  `placeDBox` text NOT NULL,
  `moreDBox` text NOT NULL,
  `thanksTxt` text NOT NULL,
  `adminMailAdress` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `#__googlemap` VALUES (1, 'My company name', 'ABQIAAAAY5An9Nrd7TgpeE132bmNoxRuOP1Ir1xxnnjJvwEzgIzlK53mZRS7EBPqFu0K8DE1tfG9j2-unTl5ag', 350, 350, 'inetlankapvt@gmail.com', '53425345', '345346436', '543253425435', 'Colombo \r\nsri lanka', '79.99651908874512', '6.690804398785493', '14', 'NORMAL', 'http://extensions.joomla.org/templates/joomla-jed08/images/logo.png', '4cePq9VqQjw', 1, 0, 0, 0, 0, 0, 'E-mail  : ', 'Hand Phone : ', 'Land Phone : ', 'Fax : ', 'Other : ', 'Other', 1, 2, 3, 4, 6, 'Enter your Name: ', 'E-mail address:', 'Message Subject: ', 'Message Subject: ', 'Type here Spam image ', 'E-mail a copy of this message to your own address.', 'send', 300, 'Place1', 'More Details1','Thanks For you','');
